// Watch API v1: keep a local projection of one PostgreSQL scope in sync,
// and know when it is fresh. See docs/semantics.md for the contract these
// messages carry.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: api/watch/v1/watch.proto

package watchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResyncReason int32

const (
	ResyncReason_RESYNC_REASON_UNSPECIFIED ResyncReason = 0
	// The resume cursor is not replayable here, for example after a server
	// restart or once the replay window moved past it.
	ResyncReason_RESYNC_REASON_CURSOR_UNAVAILABLE ResyncReason = 1
	// The client fell further behind than the server buffers for it.
	ResyncReason_RESYNC_REASON_SLOW_WATCHER ResyncReason = 2
	// The snapshot could not be paired with the change stream; a new one will.
	ResyncReason_RESYNC_REASON_SNAPSHOT_WINDOW_CLOSED ResyncReason = 3
	// The server's source stream ended.
	ResyncReason_RESYNC_REASON_SOURCE_STOPPED ResyncReason = 4
)

// Enum value maps for ResyncReason.
var (
	ResyncReason_name = map[int32]string{
		0: "RESYNC_REASON_UNSPECIFIED",
		1: "RESYNC_REASON_CURSOR_UNAVAILABLE",
		2: "RESYNC_REASON_SLOW_WATCHER",
		3: "RESYNC_REASON_SNAPSHOT_WINDOW_CLOSED",
		4: "RESYNC_REASON_SOURCE_STOPPED",
	}
	ResyncReason_value = map[string]int32{
		"RESYNC_REASON_UNSPECIFIED":            0,
		"RESYNC_REASON_CURSOR_UNAVAILABLE":     1,
		"RESYNC_REASON_SLOW_WATCHER":           2,
		"RESYNC_REASON_SNAPSHOT_WINDOW_CLOSED": 3,
		"RESYNC_REASON_SOURCE_STOPPED":         4,
	}
)

func (x ResyncReason) Enum() *ResyncReason {
	p := new(ResyncReason)
	*p = x
	return p
}

func (x ResyncReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResyncReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_watch_v1_watch_proto_enumTypes[0].Descriptor()
}

func (ResyncReason) Type() protoreflect.EnumType {
	return &file_api_watch_v1_watch_proto_enumTypes[0]
}

func (x ResyncReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResyncReason.Descriptor instead.
func (ResyncReason) EnumDescriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{0}
}

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_INSERT      Operation = 1
	Operation_OPERATION_UPDATE      Operation = 2
	Operation_OPERATION_DELETE      Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_INSERT",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_INSERT":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_watch_v1_watch_proto_enumTypes[1].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_api_watch_v1_watch_proto_enumTypes[1]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{1}
}

type CursorOrder int32

const (
	CursorOrder_CURSOR_ORDER_UNSPECIFIED CursorOrder = 0
	// left is before right.
	CursorOrder_CURSOR_ORDER_BEFORE CursorOrder = 1
	CursorOrder_CURSOR_ORDER_EQUAL  CursorOrder = 2
	// left is after right.
	CursorOrder_CURSOR_ORDER_AFTER CursorOrder = 3
)

// Enum value maps for CursorOrder.
var (
	CursorOrder_name = map[int32]string{
		0: "CURSOR_ORDER_UNSPECIFIED",
		1: "CURSOR_ORDER_BEFORE",
		2: "CURSOR_ORDER_EQUAL",
		3: "CURSOR_ORDER_AFTER",
	}
	CursorOrder_value = map[string]int32{
		"CURSOR_ORDER_UNSPECIFIED": 0,
		"CURSOR_ORDER_BEFORE":      1,
		"CURSOR_ORDER_EQUAL":       2,
		"CURSOR_ORDER_AFTER":       3,
	}
)

func (x CursorOrder) Enum() *CursorOrder {
	p := new(CursorOrder)
	*p = x
	return p
}

func (x CursorOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CursorOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_api_watch_v1_watch_proto_enumTypes[2].Descriptor()
}

func (CursorOrder) Type() protoreflect.EnumType {
	return &file_api_watch_v1_watch_proto_enumTypes[2]
}

func (x CursorOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CursorOrder.Descriptor instead.
func (CursorOrder) EnumDescriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{2}
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// projection names a projection configured on the server.
	Projection string `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	// scope is the scope column's value in PostgreSQL text form, for example a
	// tenant ID. A uuid must use its canonical lowercase form.
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// resume_cursor is a cursor from an earlier Batch or Progress, or empty to
	// start with a snapshot.
	ResumeCursor  string `protobuf:"bytes,3,opt,name=resume_cursor,json=resumeCursor,proto3" json:"resume_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *WatchRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *WatchRequest) GetResumeCursor() string {
	if x != nil {
		return x.ResumeCursor
	}
	return ""
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchResponse_SnapshotBegin
	//	*WatchResponse_SnapshotRows
	//	*WatchResponse_SnapshotEnd
	//	*WatchResponse_Batch
	//	*WatchResponse_Progress
	//	*WatchResponse_Resync
	Event         isWatchResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetEvent() isWatchResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchResponse) GetSnapshotBegin() *SnapshotBegin {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_SnapshotBegin); ok {
			return x.SnapshotBegin
		}
	}
	return nil
}

func (x *WatchResponse) GetSnapshotRows() *SnapshotRows {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_SnapshotRows); ok {
			return x.SnapshotRows
		}
	}
	return nil
}

func (x *WatchResponse) GetSnapshotEnd() *SnapshotEnd {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_SnapshotEnd); ok {
			return x.SnapshotEnd
		}
	}
	return nil
}

func (x *WatchResponse) GetBatch() *Batch {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *WatchResponse) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *WatchResponse) GetResync() *Resync {
	if x != nil {
		if x, ok := x.Event.(*WatchResponse_Resync); ok {
			return x.Resync
		}
	}
	return nil
}

type isWatchResponse_Event interface {
	isWatchResponse_Event()
}

type WatchResponse_SnapshotBegin struct {
	SnapshotBegin *SnapshotBegin `protobuf:"bytes,1,opt,name=snapshot_begin,json=snapshotBegin,proto3,oneof"`
}

type WatchResponse_SnapshotRows struct {
	SnapshotRows *SnapshotRows `protobuf:"bytes,2,opt,name=snapshot_rows,json=snapshotRows,proto3,oneof"`
}

type WatchResponse_SnapshotEnd struct {
	SnapshotEnd *SnapshotEnd `protobuf:"bytes,3,opt,name=snapshot_end,json=snapshotEnd,proto3,oneof"`
}

type WatchResponse_Batch struct {
	Batch *Batch `protobuf:"bytes,4,opt,name=batch,proto3,oneof"`
}

type WatchResponse_Progress struct {
	Progress *Progress `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type WatchResponse_Resync struct {
	Resync *Resync `protobuf:"bytes,6,opt,name=resync,proto3,oneof"`
}

func (*WatchResponse_SnapshotBegin) isWatchResponse_Event() {}

func (*WatchResponse_SnapshotRows) isWatchResponse_Event() {}

func (*WatchResponse_SnapshotEnd) isWatchResponse_Event() {}

func (*WatchResponse_Batch) isWatchResponse_Event() {}

func (*WatchResponse_Progress) isWatchResponse_Event() {}

func (*WatchResponse_Resync) isWatchResponse_Event() {}

// SnapshotBegin starts a snapshot. The projection is stale until the
// Progress that follows SnapshotEnd.
type SnapshotBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotBegin) Reset() {
	*x = SnapshotBegin{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotBegin) ProtoMessage() {}

func (x *SnapshotBegin) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotBegin.ProtoReflect.Descriptor instead.
func (*SnapshotBegin) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{2}
}

// SnapshotRows carries some of the scope's rows, in primary-key order.
type SnapshotRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRows) Reset() {
	*x = SnapshotRows{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRows) ProtoMessage() {}

func (x *SnapshotRows) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRows.ProtoReflect.Descriptor instead.
func (*SnapshotRows) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotRows) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// SnapshotEnd ends a snapshot: the rows received since SnapshotBegin now
// replace the client's projection, in one step.
type SnapshotEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnd) Reset() {
	*x = SnapshotEnd{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnd) ProtoMessage() {}

func (x *SnapshotEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnd.ProtoReflect.Descriptor instead.
func (*SnapshotEnd) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{4}
}

// Batch is the part of one committed source transaction that belongs to
// this projection and scope. Apply it whole. Batches can be delivered more
// than once, so applying one must be idempotent.
type Batch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cursor is the position just after the transaction. After applying the
	// batch, the client may persist it and resume from it.
	Cursor  string    `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Changes []*Change `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	// commit_time is when the transaction committed, by the source's clock.
	// It is informational, for measuring latency (it is subject to clock
	// skew between the source and the client): order comes only from
	// cursor. Unset when the server does not know it.
	CommitTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{5}
}

func (x *Batch) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Batch) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *Batch) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

// Progress states that every relevant committed change through cursor has
// been delivered. After applying everything before it, the client is fresh
// as of cursor, and may persist it and resume from it.
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Resync ends the stream: the client cannot continue from where it is.
type Resync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ResyncReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=watch.v1.ResyncReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resync) Reset() {
	*x = Resync{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resync) ProtoMessage() {}

func (x *Resync) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resync.ProtoReflect.Descriptor instead.
func (*Resync) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{7}
}

func (x *Resync) GetReason() ResyncReason {
	if x != nil {
		return x.Reason
	}
	return ResyncReason_RESYNC_REASON_UNSPECIFIED
}

type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values maps each column to its value.
	Values        map[string]*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{8}
}

func (x *Row) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Change struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=watch.v1.Operation" json:"operation,omitempty"`
	// table is the schema-qualified source table.
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// key identifies the row: its primary-key columns, in PostgreSQL text
	// form. A key value is never NULL.
	Key map[string]string `protobuf:"bytes,3,rep,name=key,proto3" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// values is the row's new state for an insert or update, and empty for a
	// delete.
	Values        map[string]*Value `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{9}
}

func (x *Change) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *Change) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Change) GetKey() map[string]string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Change) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Value is one column value. See "Value encoding" in docs/semantics.md.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_Text
	//	*Value_Null
	//	*Value_UnchangedToast
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{10}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Value) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *Value) GetUnchangedToast() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Kind.(*Value_UnchangedToast); ok {
			return x.UnchangedToast
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_Text struct {
	// text is the value's PostgreSQL text representation, for every type.
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Value_Null struct {
	// null is SQL NULL.
	Null structpb.NullValue `protobuf:"varint,2,opt,name=null,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Value_UnchangedToast struct {
	// unchanged_toast marks a large column an UPDATE left unchanged and did
	// not resend: keep the value the client already has.
	UnchangedToast *emptypb.Empty `protobuf:"bytes,3,opt,name=unchanged_toast,json=unchangedToast,proto3,oneof"`
}

func (*Value_Text) isValue_Kind() {}

func (*Value_Null) isValue_Kind() {}

func (*Value_UnchangedToast) isValue_Kind() {}

type CompareCursorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          string                 `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         string                 `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareCursorsRequest) Reset() {
	*x = CompareCursorsRequest{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareCursorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareCursorsRequest) ProtoMessage() {}

func (x *CompareCursorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareCursorsRequest.ProtoReflect.Descriptor instead.
func (*CompareCursorsRequest) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{11}
}

func (x *CompareCursorsRequest) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *CompareCursorsRequest) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

type CompareCursorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         CursorOrder            `protobuf:"varint,1,opt,name=order,proto3,enum=watch.v1.CursorOrder" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareCursorsResponse) Reset() {
	*x = CompareCursorsResponse{}
	mi := &file_api_watch_v1_watch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareCursorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareCursorsResponse) ProtoMessage() {}

func (x *CompareCursorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_watch_v1_watch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareCursorsResponse.ProtoReflect.Descriptor instead.
func (*CompareCursorsResponse) Descriptor() ([]byte, []int) {
	return file_api_watch_v1_watch_proto_rawDescGZIP(), []int{12}
}

func (x *CompareCursorsResponse) GetOrder() CursorOrder {
	if x != nil {
		return x.Order
	}
	return CursorOrder_CURSOR_ORDER_UNSPECIFIED
}

var File_api_watch_v1_watch_proto protoreflect.FileDescriptor

const file_api_watch_v1_watch_proto_rawDesc = "" +
	"\n" +
	"\x18api/watch/v1/watch.proto\x12\bwatch.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\fWatchRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12#\n" +
	"\rresume_cursor\x18\x03 \x01(\tR\fresumeCursor\"\xdc\x02\n" +
	"\rWatchResponse\x12@\n" +
	"\x0esnapshot_begin\x18\x01 \x01(\v2\x17.watch.v1.SnapshotBeginH\x00R\rsnapshotBegin\x12=\n" +
	"\rsnapshot_rows\x18\x02 \x01(\v2\x16.watch.v1.SnapshotRowsH\x00R\fsnapshotRows\x12:\n" +
	"\fsnapshot_end\x18\x03 \x01(\v2\x15.watch.v1.SnapshotEndH\x00R\vsnapshotEnd\x12'\n" +
	"\x05batch\x18\x04 \x01(\v2\x0f.watch.v1.BatchH\x00R\x05batch\x120\n" +
	"\bprogress\x18\x05 \x01(\v2\x12.watch.v1.ProgressH\x00R\bprogress\x12*\n" +
	"\x06resync\x18\x06 \x01(\v2\x10.watch.v1.ResyncH\x00R\x06resyncB\a\n" +
	"\x05event\"\x0f\n" +
	"\rSnapshotBegin\"1\n" +
	"\fSnapshotRows\x12!\n" +
	"\x04rows\x18\x01 \x03(\v2\r.watch.v1.RowR\x04rows\"\r\n" +
	"\vSnapshotEnd\"\x88\x01\n" +
	"\x05Batch\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12*\n" +
	"\achanges\x18\x02 \x03(\v2\x10.watch.v1.ChangeR\achanges\x12;\n" +
	"\vcommit_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\"\"\n" +
	"\bProgress\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"8\n" +
	"\x06Resync\x12.\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x16.watch.v1.ResyncReasonR\x06reason\"\x84\x01\n" +
	"\x03Row\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.watch.v1.Row.ValuesEntryR\x06values\x1aJ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.watch.v1.ValueR\x05value:\x028\x01\"\xb8\x02\n" +
	"\x06Change\x121\n" +
	"\toperation\x18\x01 \x01(\x0e2\x13.watch.v1.OperationR\toperation\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12+\n" +
	"\x03key\x18\x03 \x03(\v2\x19.watch.v1.Change.KeyEntryR\x03key\x124\n" +
	"\x06values\x18\x04 \x03(\v2\x1c.watch.v1.Change.ValuesEntryR\x06values\x1a6\n" +
	"\bKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aJ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.watch.v1.ValueR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x05Value\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x120\n" +
	"\x04null\x18\x02 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04null\x12A\n" +
	"\x0funchanged_toast\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0eunchangedToastB\x06\n" +
	"\x04kind\"A\n" +
	"\x15CompareCursorsRequest\x12\x12\n" +
	"\x04left\x18\x01 \x01(\tR\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\tR\x05right\"E\n" +
	"\x16CompareCursorsResponse\x12+\n" +
	"\x05order\x18\x01 \x01(\x0e2\x15.watch.v1.CursorOrderR\x05order*\xbf\x01\n" +
	"\fResyncReason\x12\x1d\n" +
	"\x19RESYNC_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	" RESYNC_REASON_CURSOR_UNAVAILABLE\x10\x01\x12\x1e\n" +
	"\x1aRESYNC_REASON_SLOW_WATCHER\x10\x02\x12(\n" +
	"$RESYNC_REASON_SNAPSHOT_WINDOW_CLOSED\x10\x03\x12 \n" +
	"\x1cRESYNC_REASON_SOURCE_STOPPED\x10\x04*h\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_INSERT\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03*t\n" +
	"\vCursorOrder\x12\x1c\n" +
	"\x18CURSOR_ORDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CURSOR_ORDER_BEFORE\x10\x01\x12\x16\n" +
	"\x12CURSOR_ORDER_EQUAL\x10\x02\x12\x16\n" +
	"\x12CURSOR_ORDER_AFTER\x10\x032\x9f\x01\n" +
	"\fWatchService\x12:\n" +
	"\x05Watch\x12\x16.watch.v1.WatchRequest\x1a\x17.watch.v1.WatchResponse0\x01\x12S\n" +
	"\x0eCompareCursors\x12\x1f.watch.v1.CompareCursorsRequest\x1a .watch.v1.CompareCursorsResponseB6Z4github.com/usernamenenad/watchd/api/watch/v1;watchv1b\x06proto3"

var (
	file_api_watch_v1_watch_proto_rawDescOnce sync.Once
	file_api_watch_v1_watch_proto_rawDescData []byte
)

func file_api_watch_v1_watch_proto_rawDescGZIP() []byte {
	file_api_watch_v1_watch_proto_rawDescOnce.Do(func() {
		file_api_watch_v1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_watch_v1_watch_proto_rawDesc), len(file_api_watch_v1_watch_proto_rawDesc)))
	})
	return file_api_watch_v1_watch_proto_rawDescData
}

var file_api_watch_v1_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_watch_v1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_watch_v1_watch_proto_goTypes = []any{
	(ResyncReason)(0),              // 0: watch.v1.ResyncReason
	(Operation)(0),                 // 1: watch.v1.Operation
	(CursorOrder)(0),               // 2: watch.v1.CursorOrder
	(*WatchRequest)(nil),           // 3: watch.v1.WatchRequest
	(*WatchResponse)(nil),          // 4: watch.v1.WatchResponse
	(*SnapshotBegin)(nil),          // 5: watch.v1.SnapshotBegin
	(*SnapshotRows)(nil),           // 6: watch.v1.SnapshotRows
	(*SnapshotEnd)(nil),            // 7: watch.v1.SnapshotEnd
	(*Batch)(nil),                  // 8: watch.v1.Batch
	(*Progress)(nil),               // 9: watch.v1.Progress
	(*Resync)(nil),                 // 10: watch.v1.Resync
	(*Row)(nil),                    // 11: watch.v1.Row
	(*Change)(nil),                 // 12: watch.v1.Change
	(*Value)(nil),                  // 13: watch.v1.Value
	(*CompareCursorsRequest)(nil),  // 14: watch.v1.CompareCursorsRequest
	(*CompareCursorsResponse)(nil), // 15: watch.v1.CompareCursorsResponse
	nil,                            // 16: watch.v1.Row.ValuesEntry
	nil,                            // 17: watch.v1.Change.KeyEntry
	nil,                            // 18: watch.v1.Change.ValuesEntry
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
	(structpb.NullValue)(0),        // 20: google.protobuf.NullValue
	(*emptypb.Empty)(nil),          // 21: google.protobuf.Empty
}
var file_api_watch_v1_watch_proto_depIdxs = []int32{
	5,  // 0: watch.v1.WatchResponse.snapshot_begin:type_name -> watch.v1.SnapshotBegin
	6,  // 1: watch.v1.WatchResponse.snapshot_rows:type_name -> watch.v1.SnapshotRows
	7,  // 2: watch.v1.WatchResponse.snapshot_end:type_name -> watch.v1.SnapshotEnd
	8,  // 3: watch.v1.WatchResponse.batch:type_name -> watch.v1.Batch
	9,  // 4: watch.v1.WatchResponse.progress:type_name -> watch.v1.Progress
	10, // 5: watch.v1.WatchResponse.resync:type_name -> watch.v1.Resync
	11, // 6: watch.v1.SnapshotRows.rows:type_name -> watch.v1.Row
	12, // 7: watch.v1.Batch.changes:type_name -> watch.v1.Change
	19, // 8: watch.v1.Batch.commit_time:type_name -> google.protobuf.Timestamp
	0,  // 9: watch.v1.Resync.reason:type_name -> watch.v1.ResyncReason
	16, // 10: watch.v1.Row.values:type_name -> watch.v1.Row.ValuesEntry
	1,  // 11: watch.v1.Change.operation:type_name -> watch.v1.Operation
	17, // 12: watch.v1.Change.key:type_name -> watch.v1.Change.KeyEntry
	18, // 13: watch.v1.Change.values:type_name -> watch.v1.Change.ValuesEntry
	20, // 14: watch.v1.Value.null:type_name -> google.protobuf.NullValue
	21, // 15: watch.v1.Value.unchanged_toast:type_name -> google.protobuf.Empty
	2,  // 16: watch.v1.CompareCursorsResponse.order:type_name -> watch.v1.CursorOrder
	13, // 17: watch.v1.Row.ValuesEntry.value:type_name -> watch.v1.Value
	13, // 18: watch.v1.Change.ValuesEntry.value:type_name -> watch.v1.Value
	3,  // 19: watch.v1.WatchService.Watch:input_type -> watch.v1.WatchRequest
	14, // 20: watch.v1.WatchService.CompareCursors:input_type -> watch.v1.CompareCursorsRequest
	4,  // 21: watch.v1.WatchService.Watch:output_type -> watch.v1.WatchResponse
	15, // 22: watch.v1.WatchService.CompareCursors:output_type -> watch.v1.CompareCursorsResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_watch_v1_watch_proto_init() }
func file_api_watch_v1_watch_proto_init() {
	if File_api_watch_v1_watch_proto != nil {
		return
	}
	file_api_watch_v1_watch_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchResponse_SnapshotBegin)(nil),
		(*WatchResponse_SnapshotRows)(nil),
		(*WatchResponse_SnapshotEnd)(nil),
		(*WatchResponse_Batch)(nil),
		(*WatchResponse_Progress)(nil),
		(*WatchResponse_Resync)(nil),
	}
	file_api_watch_v1_watch_proto_msgTypes[10].OneofWrappers = []any{
		(*Value_Text)(nil),
		(*Value_Null)(nil),
		(*Value_UnchangedToast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_watch_v1_watch_proto_rawDesc), len(file_api_watch_v1_watch_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_watch_v1_watch_proto_goTypes,
		DependencyIndexes: file_api_watch_v1_watch_proto_depIdxs,
		EnumInfos:         file_api_watch_v1_watch_proto_enumTypes,
		MessageInfos:      file_api_watch_v1_watch_proto_msgTypes,
	}.Build()
	File_api_watch_v1_watch_proto = out.File
	file_api_watch_v1_watch_proto_goTypes = nil
	file_api_watch_v1_watch_proto_depIdxs = nil
}
